import { NextResponse } from "next/server";

const fakeResults = [
  "I drafted a working plan for this request and broke it into a few practical steps. First, I would clarify the intended outcome and the audience. Then I would gather the minimum useful context, create a small first version, and validate it before expanding the scope. For a production workflow, this response would be generated by a real model and backed by task history, tools, and user preferences.",
  "I analyzed the prompt and found three possible directions. The fastest path is to create a simple prototype, the safer path is to write a short requirements brief first, and the most complete path is to combine research, implementation, and review into one workflow. For this POC, I am returning a longer randomized mock response so the chat screen can demonstrate streaming output and realistic message spacing.",
  "I turned the request into a concise execution brief. The goal is clear enough to start with a lightweight implementation, then refine based on user feedback. The main assumptions are that speed matters more than completeness, the output should be easy to inspect, and the interface should stay simple. A future backend could replace this fake response with model calls, retrieval, tool execution, or queued background jobs.",
  "I prepared a mock task result with enough structure to feel like an agent response. The next step would be to decide what kind of output is expected, such as a summary, a plan, a generated file, or an action taken on the user's behalf. After that, I would report progress, show the result, and offer suggested follow-ups. This placeholder keeps the product flow testable while the real API is still being designed.",
  "I mapped the task into research, planning, implementation, and validation phases. In research, I would collect relevant facts and constraints. In planning, I would choose the smallest useful deliverable. In implementation, I would produce the requested result. In validation, I would check whether the result actually satisfies the prompt. This is a randomized fake response, but it mirrors the shape of a real agentic workflow."
];

const followUps = [
  "I can also turn this into a checklist, a project brief, or a follow-up task.",
  "If this were connected to real tools, I would now save the result and suggest the next action.",
  "A full version could include citations, artifacts, live API calls, and background task status.",
  "For now, this gives the UI a more realistic response length for testing the chat experience."
];

export async function POST(request: Request) {
  const body = (await request.json().catch(() => null)) as { prompt?: unknown } | null;
  const prompt = typeof body?.prompt === "string" ? body.prompt.trim() : "";

  if (!prompt) {
    return NextResponse.json({ error: "Prompt is required." }, { status: 400 });
  }

  const result = fakeResults[Math.floor(Math.random() * fakeResults.length)];
  const followUp = followUps[Math.floor(Math.random() * followUps.length)];

  return NextResponse.json({
    prompt,
    result: `${result}\n\nPrompt received: "${prompt}"\n\n${followUp}`
  });
}
